/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewLibraCloud;

/**
 *
 * @author chika
 */
public class GestionLibraCloud extends javax.swing.JFrame {

    /**
     * Creates new form GestionLibraCloud
     */
    public GestionLibraCloud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        jMenu1.setText("Accueil");
        jMenu1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem6.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem6.setText("Vue d'ensemble");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem2.setText("Statistiques générales");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem3.setText("Alertes et notifications");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem4.setText("Tâches en attente");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem5.setText("Raccourcis personnalisables");
        jMenu1.add(jMenuItem5);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem7.setText("Quitter");
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu7.setText("Bibliothèque");
        jMenu7.setActionCommand("");
        jMenu7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenuItem8.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem8.setText("Liste des ouvrages");
        jMenu7.add(jMenuItem8);

        jMenu2.setText("Gestion du catalogue");
        jMenu2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem9.setText("Ajouter des ouvrages");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem10.setText("Modifier des ouvrages");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem11.setText("Supprimer des ouvrages");
        jMenu2.add(jMenuItem11);

        jMenu7.add(jMenu2);

        jMenuItem12.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem12.setText("Rechercher un ouvrage");
        jMenu7.add(jMenuItem12);

        jMenu3.setText("Recherche avancée");
        jMenu3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jMenuItem13.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem13.setText("Par auteur/éditeur");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem14.setText("Par genre/thématique");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem15.setText("Par ISBN");
        jMenu3.add(jMenuItem15);

        jMenu7.add(jMenu3);

        jMenu4.setText("Tarification");
        jMenu4.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem16.setText("Définition des prix de base");
        jMenu4.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem17.setText("Gestion des promotions et remises");
        jMenu4.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem18.setText("Application des taxes (TVA, autres taxes locales)");
        jMenu4.add(jMenuItem18);

        jMenuItem19.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem19.setText("Tarification dynamique (en fonction de la demande)");
        jMenu4.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem20.setText("Suivi des marges et rentabilité");
        jMenu4.add(jMenuItem20);

        jMenuItem21.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem21.setText("Gestion des prix en devises multiples");
        jMenu4.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem22.setText("Historique des modifications de prix");
        jMenu4.add(jMenuItem22);

        jMenu7.add(jMenu4);

        jMenu5.setText("Classification ");
        jMenu5.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem23.setText("Catégories principales ");
        jMenu5.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem24.setText("Sous-catégories");
        jMenu5.add(jMenuItem24);

        jMenuItem30.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem30.setText("Attribution multiple (appartenir à plusieurs catégories)");
        jMenu5.add(jMenuItem30);

        jMenuItem25.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem25.setText("Genres principaux");
        jMenu5.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem26.setText("Sous-genres");
        jMenu5.add(jMenuItem26);

        jMenuItem27.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem27.setText("Attribution multiple ( appartenir à plusieurs genres)");
        jMenu5.add(jMenuItem27);

        jMenuItem28.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem28.setText("Gestion des mots-clés associés ");
        jMenu5.add(jMenuItem28);

        jMenuItem29.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem29.setText("Mise à jour et fusion ");
        jMenu5.add(jMenuItem29);

        jMenu7.add(jMenu5);

        jMenuItem31.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem31.setText("Localisation des stocks ");
        jMenu7.add(jMenuItem31);

        jMenuItem32.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem32.setText("Suivi des déplacements de stock");
        jMenu7.add(jMenuItem32);

        jMenuItem33.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem33.setText("Étiquetage et codes-barres pour les emplacements");
        jMenu7.add(jMenuItem33);

        jMenuItem34.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem34.setText("Gestion des stocks réservés");
        jMenu7.add(jMenuItem34);

        jMenuItem35.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem35.setText("Optimisation de l’espace de stockage");
        jMenu7.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jMenuItem36.setText("Alerte réapprovisionnement emplacement ");
        jMenu7.add(jMenuItem36);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Stock");
        jMenu8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu8);

        jMenu9.setText("Caisse");
        jMenu9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu9);

        jMenu10.setText("Clients");
        jMenu10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu10);

        jMenu11.setText("Comptabilité");
        jMenu11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu11);

        jMenu12.setText("Ressources Humaines");
        jMenu12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu12);

        jMenu13.setText("Paramètres");
        jMenu13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu13);

        jMenu14.setText("Projets");
        jMenu14.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu14);

        jMenu15.setText("Statistiques");
        jMenu15.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu15);

        jMenu16.setText("Support");
        jMenu16.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jMenu16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        setSize(new java.awt.Dimension(939, 770));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLibraCloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLibraCloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLibraCloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLibraCloud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLibraCloud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
